//! Gate modules.
//!
//! # Adding a gate (read this before you touch anything)
//!
//! Create **one** file: `crates/cdcp_gate/src/gates/<your_gate>.rs`. That is the
//! entire change. Do not edit this file, `registry.rs`, `main.rs`, or any other
//! agent's gate — `build.rs` globs this directory and generates the `mod`
//! declarations and the dispatch table below.
//!
//! Your file must expose exactly three items:
//!
//! ```ignore
//! pub const NAME: &str = "verify-orphans";        // the subcommand, kebab-case
//! pub const SUMMARY: &str = "one line for `cdcp_gate list`";
//! pub fn run(ctx: &crate::registry::GateCtx) -> Result<(), crate::registry::GateError> { .. }
//! ```
//!
//! Return `GateError::Violation` when an assertion fails, `GateError::Error` when
//! the gate could not honestly evaluate (unreadable input, zero files scanned),
//! and `GateError::Usage` for a bad invocation. `crate::exit` documents the codes.
//!
//! Seventeen migration beads (bd-substrate-rust-migration-jhd.2 .. .18) land here
//! in parallel. One file each, zero shared-file collisions.

include!(concat!(env!("OUT_DIR"), "/gate_modules.rs"));
