//! Gate auto-registration codegen.
//!
//! WHY THIS EXISTS: seventeen sibling migration beads (bd-substrate-rust-migration-jhd.2
//! .. .18) each add one gate to this crate, in parallel, in the same tree. If
//! registration required editing a shared `mod.rs` or a shared `match` arm, every
//! one of those agents would collide with every other one on the same three lines.
//!
//! So registration is derived, not written: this script globs `src/gates/*.rs` and
//! emits both the `mod` declarations and the dispatch table. Adding a gate is
//! EXACTLY ONE new file — `src/gates/<name>.rs` — and no edit to any file another
//! agent owns.
//!
//! CONTRACT each gate file must satisfy (checked at compile time by the generated
//! table, and at run time by `tests/dispatch.rs`):
//!   pub const NAME: &str          // subcommand name, kebab-case
//!   pub const SUMMARY: &str       // one line for `cdcp_gate list`
//!   pub fn run(&GateCtx) -> Result<(), GateError>
//!
//! Anti-vacuous: zero gate files is a build ERROR, not an empty-but-green
//! dispatcher. A dispatcher that dispatches nothing reports exactly like one whose
//! gates all passed.

use std::collections::BTreeSet;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let gates_dir = manifest.join("src").join("gates");
    println!("cargo:rerun-if-changed=src/gates");
    println!("cargo:rerun-if-changed=build.rs");

    let mut names: BTreeSet<String> = BTreeSet::new();
    let entries = fs::read_dir(&gates_dir)
        .unwrap_or_else(|e| panic!("cdcp_gate build.rs: read {}: {e}", gates_dir.display()));
    for entry in entries {
        let entry = entry.expect("cdcp_gate build.rs: dir entry");
        let path = entry.path();
        if path.extension().and_then(|s| s.to_str()) != Some("rs") {
            continue;
        }
        let stem = path
            .file_stem()
            .and_then(|s| s.to_str())
            .expect("cdcp_gate build.rs: gate file stem")
            .to_string();
        if stem == "mod" {
            continue;
        }
        if !stem
            .chars()
            .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '_')
        {
            panic!("cdcp_gate build.rs: gate module {stem:?} must be snake_case ascii");
        }
        println!("cargo:rerun-if-changed=src/gates/{stem}.rs");
        names.insert(stem);
    }

    if names.is_empty() {
        panic!(
            "cdcp_gate build.rs: zero gate modules found in {} — an empty dispatcher is an ERROR, not a pass",
            gates_dir.display()
        );
    }

    let mut out = String::new();
    out.push_str("// @generated by crates/cdcp_gate/build.rs — do not edit.\n");
    out.push_str("// Add a gate by creating src/gates/<name>.rs. Nothing else to touch.\n\n");
    for name in &names {
        let abs = gates_dir.join(format!("{name}.rs"));
        out.push_str(&format!(
            "#[path = {}]\npub mod {name};\n",
            rust_string(&abs)
        ));
    }
    out.push_str("\n/// Every gate compiled into this binary, sorted by module name.\npub static GATES: &[crate::registry::Gate] = &[\n");
    for name in &names {
        out.push_str(&format!(
            "    crate::registry::Gate {{ name: {name}::NAME, summary: {name}::SUMMARY, run: {name}::run }},\n"
        ));
    }
    out.push_str("];\n");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    fs::write(out_dir.join("gate_modules.rs"), out).expect("cdcp_gate build.rs: write OUT_DIR");
}

fn rust_string(p: &Path) -> String {
    let s = p.to_str().expect("cdcp_gate build.rs: non-utf8 path");
    let mut q = String::from("\"");
    for c in s.chars() {
        match c {
            '"' => q.push_str("\\\""),
            '\\' => q.push_str("\\\\"),
            _ => q.push(c),
        }
    }
    q.push('"');
    q
}
